---
name: autofix.ci
on: # yamllint disable-line rule:truthy
  pull_request:
permissions:
  actions: write
  checks: write
  contents: read
  id-token: write
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      - run: |
          yarn
          yarn prettier . --list-different --write
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
        with:
          commit-message: "Apply Prettier format"
